version: "3.3"
services:

  graphite:
      image: graphiteapp/graphite-statsd
      restart: always
      ports:
          - "80:8000"
          - "2003:2003"
          - "2004:2004"
          - "2023:2023"
          - "2024:2024"
          - "8125:8125/udp"
          - "8126:8126"

  grafana:
      image: grafana/grafana
      restart: always
      ports:
          - "3000:3000"
      links:
          - graphite
      environment:
          - GF_SECURITY_ADMIN_PASSWORD=admin
      volumes:
          - ./grafana/provisioning:/etc/grafana/provisioning

  energy-monitor:
      image: fokkodriesprong/docker-alpine-cron
      links:
          - graphite
      environment:
          - CRON_STRINGS=*/1 * * * * curl -s http://192.168.1.61/a?f=j | jq .cnt -r | tr ',' '.' | xargs printf "kwh:%s|g" | nc -w 1 -u graphite 8125
